language : python

version :
  - 3.6

service :
  - postgresql

env:
 global:
  - db='testdb'

install:
  - pip install -r requirements.txt

before_script:
 - "psql -c 'create database testdb;' -U postgres"


script:
  - pytest --cov=.

after_script:
  - coveralls
  