language : python

version :
  - 3.6

service :
  - postgresql

env:
  global:
    - "APP_SETTINGS"="testing"

install:
  - pip install -r requirements.txt

before_script:
 - "psql -c 'CREATE DATABASE testdb;' -U postgres"


script:
  - pytest --cov=.

after_script:
  - coveralls
  